##################################################
# APPLICATION CONFIG
##################################################

spring.application.name=finflow-eureka-server
server.port=8761

##################################################
# EUREKA SERVER CONFIG
##################################################

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.wait-time-in-ms-when-sync-empty=0

##################################################
# ACTUATOR (GOOD PRACTICE)
##################################################

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always