##################################################
# APPLICATION CONFIGURATION
##################################################

spring.application.name=finflow-platform-service
server.port=8082

##################################################
# EUREKA CLIENT CONFIGURATION
##################################################

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

##################################################
# ACTUATOR
##################################################

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

##################################################
# CACHE CONFIG
##################################################

spring.cache.type=redis

##################################################
# REDIS CONFIG
##################################################

spring.data.redis.host=localhost
spring.data.redis.port=6379